routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/', 'CoursesController@index');

Route::resource('clients', 'ClientsController', ['except' => 'show']);

Auth::routes();

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{

    const ESTADOS_CIVIS = [
        1 => 'solteiro',
        2 => 'casado',
        3 => 'divorciado'
    ];

    const PESSOA_FISICA = 'fisica';
    const PESSOA_JURIDICA = 'juridica';

    protected $fillableFisica = [
        'data_nasc', 'sexo', 'estado_civil', 'deficiencia_fisica'
    ];

    protected $fillableJuridica = [
        'fantasia'
    ];

    protected $fillableGeneral = [
        'nome', 'documento','email','telefone','inadimplente'
    ];

//    protected $fillable = [
//        'nome', 'documento','email','telefone','inadimplente', 'data_nasc', 'sexo', 'estado_civil', 'deficiencia_fisica'
//    ];

    public static function getPessoa($value){
        return $value == Client::PESSOA_JURIDICA ? $value : Client::PESSOA_FISICA;
    }

    protected function setFillable(){
        if($this->pessoa == self::PESSOA_FISICA){
            $this->fillable(array_merge($this->fillableGeneral,$this->fillableFisica));
        }else{
            $this->fillable(array_merge($this->fillableGeneral,$this->fillableJuridica));
        }
    }

    public function fill(array $attributes)
    {
        if(!$this->pessoa){
            $this->pessoa = self::getPessoa( isSet($attributes['pessoa']) ? $attributes['pessoa'] : null );
        }
        $this->setFillable();
        return parent::fill($attributes);
    }


}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Http\Requests\ClientRequest;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::all();
        return view('clients.index', compact('clients')); //['clients' => 'Coleção de clients']
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $paramPessoa = $request->get('pessoa');
        $pessoa = Client::getPessoa($paramPessoa);

        return view('clients.create', compact('pessoa'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClientRequest $request)
    {
        $client = new Client();
        $data = $request->all();
        $data['pessoa'] = Client::getPessoa($request->get('pessoa'));
        $data['inadimplente'] = $request->has('inadimplente') ? true : false;
        $client->create($data);
        return redirect()->route('clients.index');

//        $client->nome = $request->get('nome');
//        $client->documento = $request->get('documento');
//        $client->telefone = $request->get('telefone');
//        $client->email = $request->get('email');
//        $client->data_nasc = $request->get('data_nasc');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!$client = Client::find($id)){
            throw new ModelNotFoundException("Cliente não foi encontrado");
        }
        $pessoa = $client->pessoa;
        return view('clients.edit', compact('client','pessoa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClientRequest $request, $id)
    {
        if(!$client = Client::find($id)){
            throw new ModelNotFoundException("Cliente não foi encontrado");
        }
        $data = $request->all();
        $data['inadimplente'] = $request->has('inadimplente') ? true : false;
        $client->fill($data);
        $client->save();

        return redirect()->route('clients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!$client = Client::find($id)){
            throw new ModelNotFoundException("Cliente não foi encontrado");
        }
        $client->delete();
        return redirect()->route('clients.index');
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Administração de clientes</h3>
        </div>
        <div class="row">

            <a href="{{ route('clients.create',['pessoa' => \App\Client::PESSOA_FISICA]) }}" class="">Pessoa física</a> |
            <a href="{{ route('clients.create',['pessoa' => \App\Client::PESSOA_JURIDICA]) }}" class="">Pessoa juídica</a>

            <br /><br />
            @if($errors->any())
                <ul class="alert alert-danger">
                    @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                    @endforeach
                </ul>
            @endif

            {!! Form::open(['route' => 'clients.store', 'class' => 'form-horizontal']) !!}
            <!--<form class="form-horizontal" method="post" action="{{ route('clients.store') }}">
                {{ csrf_field() }}-->
                <input type="hidden" name="pessoa" value="{{$pessoa}}"/>

                <fieldset>
                <!-- Form Name -->
                <legend>Novo cliente - {{$pessoa == \App\Client::PESSOA_JURIDICA ? 'Pessoa Jurídica' : 'Pessoa Física'}}</legend>


                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="nome">Nome</label>
                  <div class="col-md-4">
                  <input id="nome" name="nome" type="text" value="{{old('nome')}}" placeholder="Nome" class="form-control input-md">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="documento">
                      {{$pessoa == \App\Client::PESSOA_JURIDICA ? 'CNPJ' : 'CPF'}}
                  </label>
                  <div class="col-md-4">
                  <input id="documento" name="documento" value="{{old('documento')}}" type="text" placeholder="{{$pessoa == \App\Client::PESSOA_JURIDICA ? 'CNPJ' : 'CPF'}}" class="form-control input-md">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="email">E-mail</label>
                  <div class="col-md-4">
                  <input id="email" name="email" value="{{old('email')}}" type="text" placeholder="E-mail" class="form-control input-md">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="telefone">Telefone</label>
                  <div class="col-md-4">
                  <input id="telefone" name="telefone" value="{{old('telefone')}}" type="text" placeholder="Telefone" class="form-control input-md">

                  </div>
                </div>

                @if($pessoa == \App\Client::PESSOA_JURIDICA)

                    <div class="form-group">
                        <label class="col-md-4 control-label" for="telefone">Fantasia</label>
                        <div class="col-md-4">
                            <input id="fantasia" name="fantasia" value="{{old('fantasia')}}" type="text" placeholder="Nome fantasia" class="form-control input-md">

                        </div>
                    </div>

                @else
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="estado_civil">Estado civil</label>
                      <div class="col-md-4">
                        <select id="estado_civil" name="estado_civil" class="form-control">
                            <option value="0">Selecione</option>
                            @foreach(\App\Client::ESTADOS_CIVIS as $key => $value)
                              <option value="{{$key}}" {{old('estado_civil') == $key ? 'selected="selected"' : ''}}>{{$value}}</option>
                            @endforeach
                        </select>
                      </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="data_nasc">Data de nascimento</label>
                      <div class="col-md-4">
                      <input id="data_nasc" name="data_nasc" type="date" value="{{old('data_nasc')}}" placeholder="Data de nascimento" class="form-control input-md">

                      </div>
                    </div>

                    <!-- Multiple Radios -->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="sexo">Sexo</label>
                      <div class="col-md-4">
                      <div class="radio">
                        <label for="sexo-0">
                          <input type="radio" name="sexo" id="sexo-0" value="m"  {{old('sexo') == 'm' ? 'checked="checked"' : ''}}>
                          Masculino
                        </label>
                        </div>
                      <div class="radio">
                        <label for="sexo-1">
                          <input type="radio" name="sexo" id="sexo-1" value="f"  {{old('sexo') == 'f' ? 'checked="checked"' : ''}}>
                          Feminino
                        </label>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-md-4 control-label" for="deficiencia_fisica">Deficiência física</label>
                      <div class="col-md-4">
                      <input id="deficiencia_fisica" name="deficiencia_fisica" value="{{old('deficiencia_fisica')}}" type="text" placeholder="Deficiência física" class="form-control input-md">

                      </div>
                    </div>
                @endif

                <!-- Multiple Checkboxes -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="inadimplente">Inadimplente?</label>
                  <div class="col-md-4">
                  <div class="checkbox">
                    <label for="inadimplente-0">
                      <input type="checkbox" name="inadimplente" id="inadimplente-0" value="1"  {{old('inadimplente') == '1' ? 'checked="checked"' : ''}}>
                      sim
                    </label>
                    </div>
                  </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for=""></label>
                  <div class="col-md-4">
                        {!! Form::submit('Criar cliente', ['class' => 'btn btn-primary']) !!}
                      <!--<button id="" name="" class="btn btn-primary">Criar</button>-->
                  </div>
                </div>

                </fieldset>
            <!--</form>-->
            {!! Form::close() !!}


        </div>
    </div>


@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Administração de clientes</h3>
        </div>
        <div class="row">

            <br /><br />
            @if($errors->any())
                <ul class="alert alert-danger">
                    @foreach($errors->all() as $error)
                    <li>{{$error}}</li>
                    @endforeach
                </ul>
            @endif

            <form class="form-horizontal" method="post" action="{{ route('clients.update',['client' => $client->id]) }}">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <input type="hidden" name="pessoa" value="{{$pessoa}}"/>

                <fieldset>
                <!-- Form Name -->
                <legend>Novo cliente - {{$pessoa == \App\Client::PESSOA_JURIDICA ? 'Pessoa Jurídica' : 'Pessoa Física'}}</legend>


                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="nome">Nome</label>
                  <div class="col-md-4">
                  <input id="nome" name="nome" type="text" value="{{old('nome',$client->nome)}}" placeholder="Nome" class="form-control input-md">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="documento">
                      {{$pessoa == \App\Client::PESSOA_JURIDICA ? 'CNPJ' : 'CPF'}}
                  </label>
                  <div class="col-md-4">
                  <input id="documento" name="documento" value="{{old('documento',$client->documento)}}" type="text" placeholder="{{$pessoa == \App\Client::PESSOA_JURIDICA ? 'CNPJ' : 'CPF'}}" class="form-control input-md">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="email">E-mail</label>
                  <div class="col-md-4">
                  <input id="email" name="email" value="{{old('email',$client->email)}}" type="text" placeholder="E-mail" class="form-control input-md">

                  </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="telefone">Telefone</label>
                  <div class="col-md-4">
                  <input id="telefone" name="telefone" value="{{old('telefone',$client->telefone)}}" type="text" placeholder="Telefone" class="form-control input-md">

                  </div>
                </div>

                @if($pessoa == \App\Client::PESSOA_JURIDICA)

                    <div class="form-group">
                        <label class="col-md-4 control-label" for="telefone">Fantasia</label>
                        <div class="col-md-4">
                            <input id="fantasia" name="fantasia" value="{{old('fantasia',$client->fantasia)}}" type="text" placeholder="Nome fantasia" class="form-control input-md">

                        </div>
                    </div>

                @else
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="estado_civil">Estado civil</label>
                      <div class="col-md-4">
                        <select id="estado_civil" name="estado_civil" class="form-control">
                            <option value="0">Selecione</option>
                            @foreach(\App\Client::ESTADOS_CIVIS as $key => $value)
                              <option value="{{$key}}" {{old('estado_civil',$client->estado_civil) == $key ? 'selected="selected"' : ''}}>{{$value}}</option>
                            @endforeach
                        </select>
                      </div>
                    </div>

                    <!-- Text input-->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="data_nasc">Data de nascimento</label>
                      <div class="col-md-4">
                      <input id="data_nasc" name="data_nasc" type="date" value="{{old('data_nasc',$client->data_nasc)}}" placeholder="Data de nascimento" class="form-control input-md">

                      </div>
                    </div>

                    <!-- Multiple Radios -->
                    <div class="form-group">
                      <label class="col-md-4 control-label" for="sexo">Sexo</label>
                      <div class="col-md-4">
                      <div class="radio">
                        <label for="sexo-0">
                          <input type="radio" name="sexo" id="sexo-0" value="m"  {{old('sexo',$client->sexo) == 'm' ? 'checked="checked"' : ''}}>
                          Masculino
                        </label>
                        </div>
                      <div class="radio">
                        <label for="sexo-1">
                          <input type="radio" name="sexo" id="sexo-1" value="f"  {{old('sexo',$client->sexo) == 'f' ? 'checked="checked"' : ''}}>
                          Feminino
                        </label>
                        </div>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-md-4 control-label" for="deficiencia_fisica">Deficiência física</label>
                      <div class="col-md-4">
                      <input id="deficiencia_fisica" name="deficiencia_fisica" value="{{old('deficiencia_fisica',$client->deficiencia_fisica)}}" type="text" placeholder="Deficiência física" class="form-control input-md">

                      </div>
                    </div>
                @endif

                <!-- Multiple Checkboxes -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for="inadimplente">Inadimplente?</label>
                  <div class="col-md-4">
                  <div class="checkbox">
                    <label for="inadimplente-0">
                      <input type="checkbox" name="inadimplente" id="inadimplente-0" value="1"  {{old('inadimplente',$client->inadimplente) == '1' ? 'checked="checked"' : ''}}>
                      sim
                    </label>
                    </div>
                  </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                  <label class="col-md-4 control-label" for=""></label>
                  <div class="col-md-4">
                    <button id="" name="" class="btn btn-primary">Atualizar</button>
                  </div>
                </div>

                </fieldset>
            </form>


        </div>
    </div>


@endsection

resources/views/clients/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h3>Listagem de clientes</h3>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>CNPJ/CPF</th>
                    <th>Data Nasc.</th>
                    <th>E-mail</th>
                    <th>Telefone</th>
                    <th>Sexo</th>
                    <th>Ação</th>
                </tr>
                </thead>
                <tbody>
                @foreach($clients as $client)
                    <tr>
                        <td>{{$client->id}}</td>
                        <td>{{$client->nome}}</td>
                        <td>{{$client->documento}}</td>
                        <td>{{$client->data_nasc}}</td>
                        <td>{{$client->email}}</td>
                        <td>{{$client->telefone}}</td>
                        <td>{{!empty($client->sexo) ? $client->sexo : null}}</td>
                        <td>
                            <ul class="list-inline list-small">
                                <li><a href="{{ route('clients.edit', ['client' => $client->id]) }}" class="btn btn-link btn-link-small">Editar</a></li>
                                <li>|</li>
                                <li><form method="post" action="{{ route('clients.destroy',['client' => $client->id]) }}">
                                        {{ csrf_field() }}
                                        {{ method_field('DELETE') }}
                                        <button id="" name="" class="btn btn-link btn-link-small" type="submit">Excluir</button>
                                    </form></li>
                            </ul>



                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <br />
            <a href="{{ route('clients.create') }}" class="btn btn-primary right">Novo cliente</a>
        </div>
    </div>


@endsection